USE ToolDB
GO

SELECT *
FROM DBSetup.Security_Server ss
INNER JOIN DBSetup.Security_DataBase sdb ON sdb.ServerID = ss.ID
INNER JOIN DBSetup.Security_User su ON su.DataBaseID = sdb.ID
WHERE 1=1
--AND ss.ServerName IN ('devonlssqlao2','testonlssqlao2','prodonlssqlao2') 
AND ss.ServerName NOT LIKE 'prod%'
--AND  sdb.DATABASE_NAME IN ('Waves_Inc2019_NRT','Waves_Inc2019','ClientsMgmt','Waves2010','US_DBUtils','Kentico_OM')
AND su.UserName LIKE 'WAVES\EternityDevelopers'


SELECT sdb.ID, ',('+ CAST(sdb.ID AS VARCHAR(5)) +',''WAVES\EternityDevelopers'',0)'
FROM DBSetup.Security_Server ss
INNER JOIN DBSetup.Security_DataBase sdb ON sdb.ServerID = ss.ID
--INNER JOIN DBSetup.Security_User su ON su.DataBaseID = sdb.ID
WHERE 1=1
AND ss.ServerName NOT LIKE 'prod%'
--AND  sdb.DATABASE_NAME IN ('Waves_Inc2019_NRT','Waves_Inc2019','ClientsMgmt','Waves2010','US_DBUtils','Kentico_OM')


INSERT INTO DBSetup.Security_User (DataBaseID,UserName,IsSql)
VALUES 
 (149,'WAVES\EternityDevelopers',0)
,(110,'WAVES\EternityDevelopers',0)
,(129,'WAVES\EternityDevelopers',0)
,(195,'WAVES\EternityDevelopers',0)
,(152,'WAVES\EternityDevelopers',0)
,(146,'WAVES\EternityDevelopers',0)
,(141,'WAVES\EternityDevelopers',0)
,(143,'WAVES\EternityDevelopers',0)
,(137,'WAVES\EternityDevelopers',0)
,(113,'WAVES\EternityDevelopers',0)
,(115,'WAVES\EternityDevelopers',0)
,(116,'WAVES\EternityDevelopers',0)
,(118,'WAVES\EternityDevelopers',0)
,(120,'WAVES\EternityDevelopers',0)
,(122,'WAVES\EternityDevelopers',0)
,(124,'WAVES\EternityDevelopers',0)
,(127,'WAVES\EternityDevelopers',0)
,(131,'WAVES\EternityDevelopers',0)
,(139,'WAVES\EternityDevelopers',0)
,(135,'WAVES\EternityDevelopers',0)
,(133,'WAVES\EternityDevelopers',0)
,(150,'WAVES\EternityDevelopers',0)
,(111,'WAVES\EternityDevelopers',0)
,(130,'WAVES\EternityDevelopers',0)
,(196,'WAVES\EternityDevelopers',0)
,(153,'WAVES\EternityDevelopers',0)
,(147,'WAVES\EternityDevelopers',0)
,(142,'WAVES\EternityDevelopers',0)
,(144,'WAVES\EternityDevelopers',0)
,(138,'WAVES\EternityDevelopers',0)
,(112,'WAVES\EternityDevelopers',0)
,(114,'WAVES\EternityDevelopers',0)
,(117,'WAVES\EternityDevelopers',0)
,(119,'WAVES\EternityDevelopers',0)
,(121,'WAVES\EternityDevelopers',0)
,(123,'WAVES\EternityDevelopers',0)
,(125,'WAVES\EternityDevelopers',0)
,(128,'WAVES\EternityDevelopers',0)
,(132,'WAVES\EternityDevelopers',0)
,(140,'WAVES\EternityDevelopers',0)
,(136,'WAVES\EternityDevelopers',0)
,(134,'WAVES\EternityDevelopers',0)
,(17,'WAVES\EternityDevelopers',0)
,(25,'WAVES\EternityDevelopers',0)
,(23,'WAVES\EternityDevelopers',0)
,(18,'WAVES\EternityDevelopers',0)
,(22,'WAVES\EternityDevelopers',0)
,(3,'WAVES\EternityDevelopers',0)
,(4,'WAVES\EternityDevelopers',0)
,(5,'WAVES\EternityDevelopers',0)
,(6,'WAVES\EternityDevelopers',0)
,(7,'WAVES\EternityDevelopers',0)
,(8,'WAVES\EternityDevelopers',0)
,(9,'WAVES\EternityDevelopers',0)
,(10,'WAVES\EternityDevelopers',0)
,(11,'WAVES\EternityDevelopers',0)
,(12,'WAVES\EternityDevelopers',0)
,(13,'WAVES\EternityDevelopers',0)
,(14,'WAVES\EternityDevelopers',0)
,(15,'WAVES\EternityDevelopers',0)
,(16,'WAVES\EternityDevelopers',0)
,(31,'WAVES\EternityDevelopers',0)
,(32,'WAVES\EternityDevelopers',0)
,(33,'WAVES\EternityDevelopers',0)
,(34,'WAVES\EternityDevelopers',0)
,(35,'WAVES\EternityDevelopers',0)
,(36,'WAVES\EternityDevelopers',0)
,(37,'WAVES\EternityDevelopers',0)
,(38,'WAVES\EternityDevelopers',0)
,(39,'WAVES\EternityDevelopers',0)
,(40,'WAVES\EternityDevelopers',0)
,(41,'WAVES\EternityDevelopers',0)
,(42,'WAVES\EternityDevelopers',0)
,(43,'WAVES\EternityDevelopers',0)
,(44,'WAVES\EternityDevelopers',0)
,(91,'WAVES\EternityDevelopers',0)
,(92,'WAVES\EternityDevelopers',0)
,(93,'WAVES\EternityDevelopers',0)
,(94,'WAVES\EternityDevelopers',0)
,(95,'WAVES\EternityDevelopers',0)
,(78,'WAVES\EternityDevelopers',0)
,(79,'WAVES\EternityDevelopers',0)
,(80,'WAVES\EternityDevelopers',0)
,(81,'WAVES\EternityDevelopers',0)
,(82,'WAVES\EternityDevelopers',0)
,(83,'WAVES\EternityDevelopers',0)
,(84,'WAVES\EternityDevelopers',0)
,(85,'WAVES\EternityDevelopers',0)
,(86,'WAVES\EternityDevelopers',0)
,(87,'WAVES\EternityDevelopers',0)
,(88,'WAVES\EternityDevelopers',0)
,(89,'WAVES\EternityDevelopers',0)
,(90,'WAVES\EternityDevelopers',0)
,(96,'WAVES\EternityDevelopers',0)
,(97,'WAVES\EternityDevelopers',0)
,(98,'WAVES\EternityDevelopers',0)
,(99,'WAVES\EternityDevelopers',0)
,(100,'WAVES\EternityDevelopers',0)
,(101,'WAVES\EternityDevelopers',0)
,(102,'WAVES\EternityDevelopers',0)
,(103,'WAVES\EternityDevelopers',0)
,(104,'WAVES\EternityDevelopers',0)
,(105,'WAVES\EternityDevelopers',0)
,(106,'WAVES\EternityDevelopers',0)
,(107,'WAVES\EternityDevelopers',0)
,(108,'WAVES\EternityDevelopers',0)
,(109,'WAVES\EternityDevelopers',0)
,(172,'WAVES\EternityDevelopers',0)
,(154,'WAVES\EternityDevelopers',0)
,(163,'WAVES\EternityDevelopers',0)
,(197,'WAVES\EternityDevelopers',0)
,(173,'WAVES\EternityDevelopers',0)
,(171,'WAVES\EternityDevelopers',0)
,(169,'WAVES\EternityDevelopers',0)
,(170,'WAVES\EternityDevelopers',0)
,(167,'WAVES\EternityDevelopers',0)
,(155,'WAVES\EternityDevelopers',0)
,(156,'WAVES\EternityDevelopers',0)
,(157,'WAVES\EternityDevelopers',0)
,(158,'WAVES\EternityDevelopers',0)
,(159,'WAVES\EternityDevelopers',0)
,(160,'WAVES\EternityDevelopers',0)
,(161,'WAVES\EternityDevelopers',0)
,(162,'WAVES\EternityDevelopers',0)
,(164,'WAVES\EternityDevelopers',0)
,(168,'WAVES\EternityDevelopers',0)
,(166,'WAVES\EternityDevelopers',0)
,(165,'WAVES\EternityDevelopers',0)
,(192,'WAVES\EternityDevelopers',0)
,(174,'WAVES\EternityDevelopers',0)
,(183,'WAVES\EternityDevelopers',0)
,(198,'WAVES\EternityDevelopers',0)
,(193,'WAVES\EternityDevelopers',0)
,(191,'WAVES\EternityDevelopers',0)
,(189,'WAVES\EternityDevelopers',0)
,(190,'WAVES\EternityDevelopers',0)
,(187,'WAVES\EternityDevelopers',0)
,(175,'WAVES\EternityDevelopers',0)
,(176,'WAVES\EternityDevelopers',0)
,(177,'WAVES\EternityDevelopers',0)
,(178,'WAVES\EternityDevelopers',0)
,(179,'WAVES\EternityDevelopers',0)
,(180,'WAVES\EternityDevelopers',0)
,(181,'WAVES\EternityDevelopers',0)
,(182,'WAVES\EternityDevelopers',0)
,(184,'WAVES\EternityDevelopers',0)
,(188,'WAVES\EternityDevelopers',0)
,(186,'WAVES\EternityDevelopers',0)
,(185,'WAVES\EternityDevelopers',0)
,(57,'WAVES\EternityDevelopers',0)
,(58,'WAVES\EternityDevelopers',0)
,(59,'WAVES\EternityDevelopers',0)
,(60,'WAVES\EternityDevelopers',0)
,(61,'WAVES\EternityDevelopers',0)
,(62,'WAVES\EternityDevelopers',0)
,(45,'WAVES\EternityDevelopers',0)
,(46,'WAVES\EternityDevelopers',0)
,(47,'WAVES\EternityDevelopers',0)
,(49,'WAVES\EternityDevelopers',0)
,(50,'WAVES\EternityDevelopers',0)
,(51,'WAVES\EternityDevelopers',0)
,(52,'WAVES\EternityDevelopers',0)
,(76,'WAVES\EternityDevelopers',0)
,(54,'WAVES\EternityDevelopers',0)
,(53,'WAVES\EternityDevelopers',0)
,(56,'WAVES\EternityDevelopers',0)
,(64,'WAVES\EternityDevelopers',0)
,(63,'WAVES\EternityDevelopers',0)
,(65,'WAVES\EternityDevelopers',0)
,(66,'WAVES\EternityDevelopers',0)
,(67,'WAVES\EternityDevelopers',0)
,(68,'WAVES\EternityDevelopers',0)
,(69,'WAVES\EternityDevelopers',0)
,(70,'WAVES\EternityDevelopers',0)
,(71,'WAVES\EternityDevelopers',0)
,(72,'WAVES\EternityDevelopers',0)
,(73,'WAVES\EternityDevelopers',0)
,(74,'WAVES\EternityDevelopers',0)
,(75,'WAVES\EternityDevelopers',0)